version: "3.8"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:${NACOS_VERSION}
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    ports:
      # - "7848:7848"
      - "8848:8848"
      - "9848:9848"
      # - "9849:9849"
    env_file:
      - ../env/nacos-hostname.env
    # restart: always
    depends_on:
      mysql8_nacos:
        condition: service_healthy

  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos2
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    ports:
      # - "7858:7848"
      - "8858:8848"
      - "9858:9848"
      # - "9859:9849"
    env_file:
      - ../env/nacos-hostname.env
    # restart: always
    depends_on:
      mysql8_nacos:
        condition: service_healthy
  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos3
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
    ports:
      # - "7868:7848"
      - "8868:8848"
      - "9868:9848"
      # - "9869:9849"
    env_file:
      - ../env/nacos-hostname.env
    # restart: always
    depends_on:
      mysql8_nacos:
        condition: service_healthy
  mysql8_nacos:
    container_name: mysql8_nacos
    build:
      context: .
      dockerfile: ./image/mysql/8/Dockerfile
    image: example/mysql:8.0.30
    env_file:
      - ../env/mysql.env
    volumes:
      - mysql8-nacos:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql8-nacos:
    driver: local
